# Django Application Deployment (Green Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: messaging-app
      version: green
  template:
    metadata:
      labels:
        app: messaging-app
        version: green
    spec:
      initContainers:
      - name: init-db-wait
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z db 3306; do echo waiting for db; sleep 2; done;']
      containers:
      - name: messaging-app
        image: messaging-app:v2
        env:
        - name: DB_HOST
          value: "db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        ports:
        - containerPort: 8000