pipeline {
    agent {
        docker {
            image 'jenkins/jenkins:lts-jdk17'
            args '-u 0:0'
        }
    }
    environment {
        DOCKERHUB_USERNAME = 'wilsonfrankie'
        IMAGE_NAME = "messaging-app"
    }
    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/FrankieWilson1/alx-backend-python.git', branch: 'main'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y python3 python3-pip
                '''
            }
        }
        stage('Run Tests and Generate Report') {
            steps {
                dir('messaging_app') {
                    sh '''
                        # Install dependencies and run pytest
                        python3 -m venv venv
                        source venv/bin/activate
                        pip install -r requirements.txt
                        pytest --junitxml=test-reports/junit-report.xml
                    '''
                }
                // This step must be within the `steps` block.
                junit 'messaging_app/test-reports/junit-report.xml'
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                    sh "docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${env.BUILD_NUMBER} ./messaging_app"
                    sh "docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${env.BUILD_NUMBER}"
                }
            }
        }
    }
}
