pipeline {
    agent {
        docker {
            image 'jenkins/jenkins:lts'
            args '-u: 0:0'
        }
    }
    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: 'github-credentials', url: 'https://github.com/FrankieWilson1/alx-backend-python', branch: 'main'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                    apt-get update
                    apt-get install -y python3 python3-pip
                '''
            }
        }
        stage('Run Tests') {
            steps {
                dir('messaging_app') {
                    sh '''
                        python3 -m venv venv
                        source venv/bin/activate
                        pip3 install -r messaging_app/requirements.txt
                        pytest --junitxml=test-reports/junit-report.xml
                        deactivate
                    '''
                }
            }
            junit 'messaging_app/test-reports/junit-report.xml'
        }
    }
}