#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status.
set -e

#   Scale the Django app to 3 Replicas
echo "Scaling the messaging-app deploymet to 3 replicas..."
kubectl scale deployment messaging-app-deployment --replicas=3
echo "Scaling command sent. Waiting for pods to be ready..."

# Give Kubernetes time to create the new pods
sleep 20

# Verify the running pods
echo "Verifying that 3 pods are running: "
kubectl get pods

# Perform Load Testing with wrk
echo "Starting load test with wrk..."

echo "Installing wrk tool..."
sudo apt-get install -y wrk

echo "Enabling matrics-server in minikube..."
minikube addons enable metrics-server

SERVICE_IP=$(kubectl get svc messaging-app-service -o jsonpath='{.spec.clusterIP}')
SERVICE_PORT=80

wrk -t4 -c100 -d30s "http://$SERVICE_IP:$SERVICE_PORT/api/v1/"

# Monitor Resource Usage with kubectl top
echo "Monitoring resource usage of the pods:"
kubectl top pod
