services:
  web:
    image: messaging-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DB: messaging_app_db
      MYSQL_USER: messaging_app_user
      MYSQL_PASSWORD: some_secure_password
      MYSQL_ROOT_PASSWORD: another_secure_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: