pipeline {
    agent {
        docker {
            image 'docker/compose:1.29.2'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Build and Run Tests') {
            steps {
                echo 'Building Docker image and running tests...'
                sh 'docker-compose build web'
                sh 'docker-compose up -d'
                sh 'docker-compose exec web python manage.py test'
            }
        }
    }
}
