pipeline {
    agent any

    stages {
        stage('Install Docker Compose') {
            steps {
                echo 'Installing Docker Compose...'
                sh 'apk add --no-cache docker-compose'
            }
        }
    }

    stages {
        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                sh 'docker-compose build web'
            }
        }

        stage('Run Test') {
            steps {
                echo 'Running Django Tests...'
                sh 'docker-compose exec web python manage.py test'
            }
        }
        // deploy stage
    }
}

