apiVersion: v1
kind: Service
metadata:
  name: messaging-app-bg-service
spec:
  selector:
    app: messaging-app
    version: blue # The service initially targets the "blue" version
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/v1/
        pathType: Prefix
        backend:
          service:
            name: messaging-app-bg-service
            port:
              number: 80