apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
stringData:
  MYSQL_USER: "messaging_app_user"
  MYSQL_PASSWORD: "some_secure_password"
  MYSQL_DATABASE: "messaging_app_db"